//
//  Language.swift
//  YandexTranslator
//
//  Created by Анастасия Соколан on 02.02.19.
//  Copyright © 2019 Анастасия Соколан. All rights reserved.
//

import Foundation

enum Language: String {
    case az  = "az"
    case sq  = "sq"
    case am  = "am"
    case en  = "en"
    case ar  = "ar"
    case hy  = "hy"
    case af  = "af"
    case eu  = "eu"
    case ba  = "ba"
    case be  = "be"
    case bn  = "bn"
    case my  = "my"
    case bg  = "bg"
    case bs  = "bs"
    case cy  = "cy"
    case hu  = "hu"
    case vi  = "vi"
    case ht  = "ht"
    case gl  = "gl"
    case nl  = "nl"
    case mrj = "mrj"
    case el  = "el"
    case ka  = "ka"
    case gu  = "gu"
    case da  = "da"
    case he  = "he"
    case yi  = "yi"
    case id  = "id"
    case ga  = "ga"
    case it  = "it"
    case is_ = "is"
    case es  = "es"
    case kk  = "kk"
    case kn  = "kn"
    case ca  = "ca"
    case ky  = "ky"
    case zh  = "zh"
    case ko  = "ko"
    case xh  = "xh"
    case km  = "km"
    case lo  = "lo"
    case la  = "la"
    case lv  = "lv"
    case lt  = "lt"
    case lb  = "lb"
    case mg  = "mg"
    case ms  = "ms"
    case ml  = "ml"
    case mt  = "mt"
    case mk  = "mk"
    case mi  = "mi"
    case mr  = "mr"
    case mhr = "mhr"
    case mn  = "mn"
    case de  = "de"
    case ne  = "ne"
    case no  = "no"
    case pa  = "pa"
    case pap = "pap"
    case fa  = "fa"
    case pl  = "pl"
    case pt  = "pt"
    case ro  = "ro"
    case ru  = "ru"
    case ceb = "ceb"
    case sr  = "sr"
    case si  = "si"
    case sk  = "sk"
    case sl  = "sl"
    case sw  = "sw"
    case su  = "su"
    case tg  = "tg"
    case th  = "th"
    case tl  = "tl"
    case ta  = "ta"
    case tt  = "tt"
    case te  = "te"
    case tr  = "tr"
    case udm = "udm"
    case uz  = "uz"
    case uk  = "uk"
    case ur  = "ur"
    case fi  = "fi"
    case fr  = "fr"
    case hi  = "hi"
    case hr  = "hr"
    case cs  = "cs"
    case sv  = "sv"
    case gd  = "gd"
    case et  = "et"
    case eo  = "eo"
    case jv  = "jv"
    case ja  = "ja"
    
    case any = "any"
}
